# Sentence Completion by Using LSTM :

LSTM stands for long short-term memory networks, used in the field of Deep Learning.
It is a variety of recurrent neural networks (RNNs) that are capable of learning long-term dependencies, especially in sequence prediction problems.
It is not one algorithm but combinations of various algorithms which allows us to do complex operations on data.

Author : Prasad Patharvat

# Import Libraries

In [1]:
from warnings import filterwarnings
filterwarnings ("ignore")

from keras.preprocessing.text import Tokenizer
from keras.layers import Embedding,LSTM,Dense
from keras.models import Sequential

import pickle
import numpy as np 
import os

# Read Dataset

In [2]:
file = open("C:Downloads/wings-of-fire-by-abdul-kalam-printers1.txt","r",encoding = "utf8")

#store file in list
lines = []
for i in file:
    lines.append(i)

In [3]:
lines

['   \n',
 '\n',
 'Autobiography\n',
 'Arun Tiwari\n',
 '\x0cWINGS OF FIRE\n',
 'V fi OP nh ere ~a\\s apy\n',
 '\n',
 '\' " Pe 1D\n',
 ';\n',
 '\n',
 'NO.1 BESTSELLER\n',
 '\n',
 ' \n',
 '\x0c\x0cWINGS OF FIRE\n',
 '\n',
 'An Autobiography\n',
 '\n',
 'AVUL PAKIR JAINULABDEEN ABDUL KALAM has\n',
 'come to personally represent to many of his countrymen the\n',
 'best aspects of Indian life. Born in 1931, the son of a litte\n',
 'educated boatowner in Rameswaram, Tamilnadu, he had\n',
 'an unparalleled career as a defence scientist, culminating\n',
 'inthe highest civilan award of India, the Bharat Ratna\n',
 '\n',
 "As chief of the country's defence research and\n",
 'development programme, Kalam demonstrated the great\n',
 'potential for dynamism and innovation that ested in\n',
 'seemingly moribund research establishments. This is the\n',
 "story of Kalam's rise from obscurity and his personal and\n",
 'professional struggles, as well as the story of Agni, Prithvi,\n',
 'Akash, Trishu

In [4]:
#Convert List to string

data = ""
for i in lines:
    data = ' '.join(lines)

In [5]:
data

'   \n \n Autobiography\n Arun Tiwari\n \x0cWINGS OF FIRE\n V fi OP nh ere ~a\\s apy\n \n \' " Pe 1D\n ;\n \n NO.1 BESTSELLER\n \n  \n \x0c\x0cWINGS OF FIRE\n \n An Autobiography\n \n AVUL PAKIR JAINULABDEEN ABDUL KALAM has\n come to personally represent to many of his countrymen the\n best aspects of Indian life. Born in 1931, the son of a litte\n educated boatowner in Rameswaram, Tamilnadu, he had\n an unparalleled career as a defence scientist, culminating\n inthe highest civilan award of India, the Bharat Ratna\n \n As chief of the country\'s defence research and\n development programme, Kalam demonstrated the great\n potential for dynamism and innovation that ested in\n seemingly moribund research establishments. This is the\n story of Kalam\'s rise from obscurity and his personal and\n professional struggles, as well as the story of Agni, Prithvi,\n Akash, Trishul and Nag -missiles that have become\n household names in India and that have raised the nation to\n the level of a mis

In [6]:
#Replace uncessary stuff with space
import re
data1 = []
for i in data.split(" "):
    data1.append(re.sub("[^a-zA-Z0-9 ]","",i))

    
data1 = data1[:1000]
data = ' '.join(data1)
data[:500]

'     Autobiography Arun Tiwari WINGS OF FIRE V fi OP nh ere as apy    Pe 1D   NO1 BESTSELLER    WINGS OF FIRE  An Autobiography  AVUL PAKIR JAINULABDEEN ABDUL KALAM has come to personally represent to many of his countrymen the best aspects of Indian life Born in 1931 the son of a litte educated boatowner in Rameswaram Tamilnadu he had an unparalleled career as a defence scientist culminating inthe highest civilan award of India the Bharat Ratna  As chief of the countrys defence research and dev'

In [7]:
data

'     Autobiography Arun Tiwari WINGS OF FIRE V fi OP nh ere as apy    Pe 1D   NO1 BESTSELLER    WINGS OF FIRE  An Autobiography  AVUL PAKIR JAINULABDEEN ABDUL KALAM has come to personally represent to many of his countrymen the best aspects of Indian life Born in 1931 the son of a litte educated boatowner in Rameswaram Tamilnadu he had an unparalleled career as a defence scientist culminating inthe highest civilan award of India the Bharat Ratna  As chief of the countrys defence research and development programme Kalam demonstrated the great potential for dynamism and innovation that ested in seemingly moribund research establishments This is the story of Kalams rise from obscurity and his personal and professional struggles as well as the story of Agni Prithvi Akash Trishul and Nag missiles that have become household names in India and that have raised the nation to the level of a missile power of international recokoning  At the same time as he has helped create Indias awesome weapo

In [8]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])

#Saving the tokenizer for predict function
pickle.dump(tokenizer, open('token.pkl','wb'))

sequence_data = tokenizer.texts_to_sequences([data])[0]
sequence_data[:15]

[60, 61, 62, 63, 2, 64, 108, 109, 110, 111, 112, 13, 113, 114, 115]

In [9]:
len(sequence_data)

963

In [10]:
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)

501


In [11]:
len(np.unique(data1))

533

In [12]:
sequence = []

for i in range(3, len(sequence_data)):
    words = sequence_data[i-3:i+1]
    sequence.append(words)
    
print("The LEngth of sequence are ", len(sequence))
sequence = np.array(sequence)
sequence[:10]

The LEngth of sequence are  960


array([[ 60,  61,  62,  63],
       [ 61,  62,  63,   2],
       [ 62,  63,   2,  64],
       [ 63,   2,  64, 108],
       [  2,  64, 108, 109],
       [ 64, 108, 109, 110],
       [108, 109, 110, 111],
       [109, 110, 111, 112],
       [110, 111, 112,  13],
       [111, 112,  13, 113]])

In [13]:
X = []
y = []

for i in sequence:
    X.append(i[0:3])
    y.append(i[3])
    
X = np.array(X)
y = np.array(y)

In [14]:
print("Data: ",X[:10])
print("Response: ",y[:10])

Data:  [[ 60  61  62]
 [ 61  62  63]
 [ 62  63   2]
 [ 63   2  64]
 [  2  64 108]
 [ 64 108 109]
 [108 109 110]
 [109 110 111]
 [110 111 112]
 [111 112  13]]
Response:  [ 63   2  64 108 109 110 111 112  13 113]


In [15]:
from keras.utils.np_utils import to_categorical

In [16]:
y = to_categorical(y,num_classes=vocab_size)
y[:5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [17]:
model = Sequential()
model.add(Embedding(vocab_size,10,input_length=3))
model.add(LSTM(1000,return_sequences=True))
model.add(LSTM(1000))
model.add(Dense(1000,activation="relu"))
model.add(Dense(vocab_size,activation="softmax"))

In [18]:
model.compile(loss="categorical_crossentropy",optimizer="Adam")
model.fit(X,y,epochs=70,batch_size=64)

Epoch 1/70
15/15 [==============================] - 6s 193ms/step - loss: 6.1416
Epoch 2/70
15/15 [==============================] - 3s 192ms/step - loss: 5.7465
Epoch 3/70
15/15 [==============================] - 3s 195ms/step - loss: 5.6464
Epoch 4/70
15/15 [==============================] - 3s 233ms/step - loss: 5.5621
Epoch 5/70
15/15 [==============================] - 4s 234ms/step - loss: 5.4671
Epoch 6/70
15/15 [==============================] - 3s 232ms/step - loss: 5.3455
Epoch 7/70
15/15 [==============================] - 3s 231ms/step - loss: 5.2401
Epoch 8/70
15/15 [==============================] - 3s 233ms/step - loss: 5.1718
Epoch 9/70
15/15 [==============================] - 3s 228ms/step - loss: 5.1365
Epoch 10/70
15/15 [==============================] - 3s 227ms/step - loss: 5.0549
Epoch 11/70
15/15 [==============================] - 3s 227ms/step - loss: 5.0063
Epoch 12/70
15/15 [==============================] - 3s 230ms/step - loss: 4.9617
Epoch 13/70
15/15 [======

In [19]:
tokenizer = pickle.load(open('token.pkl', 'rb'))

In [22]:

def Predict_Next_Words(model, tokenizer, text):
    

    sequence = tokenizer.texts_to_sequences([text])
    sequence = np.array(sequence)
    preds = np.argmax(model.predict(sequence))
    predicted_word = ""
  
    for key, value in tokenizer.word_index.items():
            if value == preds:
                predicted_word = key
                break
  
    print(predicted_word)
    return predicted_word

In [ ]:
while(True):
    text = input("Enter your line: ")
  
    if text == "0":
        print("Execution completed.....")
        break
  
    else:
        try:
            text = text.split(" ")
            text = text[-3:]
            print(text)
        
            Predict_Next_Words(model, tokenizer, text)
          
        except Exception as e:
            print("Error occurred: ",e)
            continue

Enter your line: i leared how to check a 
['check', 'a', '']
1/1 [==============================] - 0s 32ms/step
sarabhai
Enter your line: crankshaft for
['crankshaft', 'for']
1/1 [==============================] - 0s 16ms/step
sarabhai
Enter your line: alibrations of a fixedpitch
['of', 'a', 'fixedpitch']
1/1 [==============================] - 1s 865ms/step
my
